baseurl = "http://www.lspy.fr"
title = "LSPY"
theme = "hugo-coder"
languagecode = "fr"
defaultcontentlanguage = "fr"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "LSPY"
    info = "Association loi 1901"
    description = "Assoctiation lois 1901"
    keywords = ""
    avatarurl = "img/logo.png"
    favicon_32 = "img/favicon-32x32.png"
    favicon_16 = "img/favicon-16x16.png"

    footercontent = "France."

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]
    colorscheme = "auto"

# Social links
#[[params.social]]
#    name = "Linkedin"
#    icon = "fab fa-linkedin fa-2x"
#    weight = 3
#    url = "https://www.linkedin.com/in/borislassort/"
#[[params.social]]
#    name = "Github"
#    icon = "fab fa-github fa-2x"
#    weight = 1
#    url = "https://github.com/borislassort/"
#[[params.social]]
#    name = "Twitter"
#    icon = "fab fa-twitter fa-2x"
#    weight = 3
#    url = "https://twitter.com/borislassort/"


# Menu links
#[[menu.main]]
#    name = "Contact"
#    weight = 1
#    url  = "/contact/"
#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"

